# run with -K to get root access where needed (become: yes)
# "--skip-tags laptop" when not installing on laptop

- hosts: localhost
  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"
    current_user: "{{ lookup('env', 'USER') }}"
  pre_tasks:
    - name: Update pacman
      pacman:
        update_cache: yes
        state: present
      become: yes
  post_tasks:
    - name: upgrade system
      yay:
        upgrade: yes
        state: present
      become: yes
  tasks:
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/utils-setup.yml
    - include_tasks: tasks/core-packages.yml
    - include_tasks: tasks/npm-globals.yml
    - include_tasks: tasks/user-setup.yml
