- hosts: localhost
  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"
  # pre_tasks:
  #   - name: Update pacman
  #     become: true
  #     pacman:
  #       update_cache: yes
  #       state: present
  tasks:
    - include: tasks/dotfiles.yml
