- name: core-packages install
  pacman:
    name:
      [
        "firefox",
        "discord",
        "thunar",
        "thunar-archive-plugin",
        "rofi",
        "redshift",
      ]
    state: latest
  become: yes

- name: dev-packages install
  pacman:
    name:
      [
        "nodejs-lts-gallium",
        "npm",
        "go",
        "gopls",
        "rustup",
        "rust-analyzer",
        "php",
        "jdk17-openjdk",
      ]
    state: latest
  become: yes

- name: dev-utils install
  pacman:
    name: ["wireshark-qt", "docker", "docker-compose"]
    state: latest
  become: yes

- name: virt-manager install
  pacman:
    name: ["virt-manager", "qemu-desktop", "libvirt", "dnsmasq", "bridge-utils"]
    state: latest
  become: yes
