- name: core-packages install
  pacman:
    name:
      [
        "firefox",
        "chromium",
        "discord",
        "thunar",
        "thunar-archive-plugin",
        "rofi",
        "redshift",
        "xclip",
        "flameshot",
        "polybar",
        "i3-gaps",
        "flatpak",
        "gimp",
        "blender",
        "inkscape",
        "darktable",
        "papirus-icon-theme",
        "rclone",
        "ttf-noto-nerd",
      ]
    state: latest
  become: yes

- name: dev-packages install
  pacman:
    name:
      [
        "nodejs-lts-hydrogen",
        "npm",
        "go",
        "rustup",
        "clang",
        "dotnet-sdk",
        "jdk17-openjdk",
        "intellij-idea-community-edition",
      ]
    state: latest
  become: yes

- name: dev-utils install
  pacman:
    name: ["wireshark-qt", "docker", "docker-compose"]
    state: latest
  become: yes

- name: virt-manager install
  pacman:
    name: ["virt-manager", "qemu-desktop", "libvirt", "dnsmasq", "bridge-utils"]
    state: latest
  become: yes
