- name: Install stow
  pacman: name=stow state=latest
  become: yes

- name: Get dotfiles
  ansible.builtin.git:
    repo: git@github.com:tremar123/.dotfiles.git
    dest: "{{ home_dir }}/.dotfiles"

- name: Stow deez nuts
  shell: "stow -d {{ home_dir }}/.dotfiles -t {{ home_dir }} -R ."
