- name: Install stow
  pacman: name=stow state=latest
  become: yes

- name: mkdir spicetify
  file:
    path: "{{ home_dir }}/.config/spicetify"
    state: directory

- name: mkdir rofi
  file:
    path: "{{ home_dir }}/.local/share/rofi"
    state: directory

- name: Get dotfiles
  ansible.builtin.git:
    repo: https://github.com/tremar123/.dotfiles
    dest: "{{ home_dir }}/.dotfiles"

- name: Stow deez nuts
  shell: "stow -d {{ home_dir }}/.dotfiles -t {{ home_dir }} -R ."
