- name: Install stow
  pacman: name=stow state=latest

- name: Get dotfiles
  ansible.builtin.git:
    repo: https://github.com/tremar123/.dotfiles.git
    dest: "{{ home_dir }}/.dotfiles"

- name: Stow theez nuts
  shell: "stow -d {{ home_dir }}/.dotfiles -t {{ home_dir }} -R ."
