# i hate my life after writing this
- name: npm - prettier
  npm:
    name: prettier
    global: yes
    state: latest

- name: npm - typescript
  npm:
    name: typescript
    global: yes
    state: latest

- name: npm - typescript-language-server
  npm:
    name: typescript-language-server
    global: yes
    state: latest

- name: npm - pyright
  npm:
    name: pyright
    global: yes
    state: latest

- name: npm - vscode-langservers-extracted
  npm:
    name: vscode-langservers-extracted
    global: yes
    state: latest

- name: npm - @tailwindcss/language-server
  npm:
    name: "@tailwindcss/language-server"
    global: yes
    state: latest

- name: npm - @prisma/language-server
  npm:
    name: "@prisma/language-server"
    global: yes
    state: latest

- name: npm - sass
  npm:
    name: sass
    global: yes
    state: latest

- name: npm -@astrojs/language-server
  npm:
    name: "@astrojs/language-server"
    global: yes
    state: latest

- name: npm caniuse-cmd
  npm:
    name: caniuse-cmd
    global: yes
    state: latest

- name: npm docker-lsp
  npm:
    name: dockerfile-language-server-nodejs
    global: yes
    state: latest

- name: npm yaml-lsp
  npm:
    name: yaml-language-server
    global: yes
    state: latest

- name: ansible-lsp
  npm:
    name: "@ansible/ansible-language-server"
    global: yes
    state: latest

- name: sql-lsp
  npm:
    name: "sql-language-server"
    global: yes
    state: latest

- name: awk-lsp
  npm:
    name: "awk-language-server"
    global: yes
    state: latest

- name: bash-lsp
  npm:
    name: "bash-language-server"
    global: yes
    state: latest
