- name: setup group docker
  group:
    name: docker
    state: present
  become: yes

- name: setup group libvirt
  group:
    name: libvirt
    state: present
  become: yes

- name: user setup
  user:
    name: "{{ current_user }}"
    groups: docker,libvirt,video
    append: yes # don't forget this one
  become: yes
