- name: Install basic utils
  pacman:
    name: ["alacritty", "neovim", "htop", "zsh", "tree", "xclip", "ripgrep", "tmux", "ranger"]
    state: latest
  become: yes

- name: Laptop utils
  pacman:
    name: ["light", "bluez", "bluez-utils", "blueman"]
    state: latest
  become: yes

- name: Install vim-plug
  shell: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  tags:
    - vim-plug

- name: set zsh as default shell
  shell: chsh -s $(which zsh)
  become: yes
