- name: Install basic utils
  pacman:
    name:
      [
        "alacritty",
        "neovim",
        "htop",
        "zsh",
        "zsh-syntax-highlighting",
        "tree",
        "ripgrep",
        "tmux",
        "ranger",
      ]
    state: latest
  become: yes

- name: Laptop utils
  pacman:
    name: ["bluez", "bluez-utils", "blueman"]
    state: latest
  become: yes

- name: Install tpm
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{ home_dir }}/.tmux/plugins/tpm"

- name: set zsh as default shell
  shell: "chsh -s $(which zsh) {{current_user}}"
  become: yes
