- name: Install basic utils
  pacman:
    name: ["alacritty", "neovim", "htop", "zsh", "tree", "xclip", "ripgrep", "tmux", "ranger"]
    state: latest
  become: yes

- name: Laptop utils
  pacman:
    name: ["light", "bluez", "bluez-utils", "blueman"]
    state: latest
  become: yes

- name: Install packer
  ansible.builtin.git:
      repo: 'https://github.com/wbthomason/packer.nvim'
      dest: "{{ home_dir }}/.local/share/nvim/site/pack/packer/start/packer.nvim"

- name: set zsh as default shell
  shell: "chsh -s $(which zsh) {{current_user}}"
  become: yes
