- name: Install basic utils
  pacman:
    name: ["alacritty", "neovim", "htop", "zsh", "tree", "xclip", "ripgrep"]
    state: latest
  become: yes

- name: Laptop utils
  yay:
    name: ["light", "optimus-manager"]
    state: latest
  become: yes
  tags:
    - laptop

- name: Install vim-plug
  shell: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  tags:
    - vim-plug
